// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrwqvsqmunjyaggisdux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yd3F2c3FtdW5qeWFnZ2lzZHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTEyMzgsImV4cCI6MjA2MTQ4NzIzOH0.uwEL-IWtv6ZClnt7VdOXas29hqG3f9J-V9iLax_Bv5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
